# ---- Builder Stage ----
FROM node:22-alpine AS builder

RUN npm install -g pnpm

ARG ROOT_DIR=.
WORKDIR /app

# Copy everything for monorepo support
COPY . .
WORKDIR /app/${ROOT_DIR}

RUN pnpm install --frozen-lockfile
RUN pnpm run build
