# ---- Builder Stage ----
FROM oven/bun:latest AS builder

ARG ROOT_DIR=.
WORKDIR /app

# Copy everything to support monorepo structures
COPY . .
WORKDIR /app/${ROOT_DIR}

RUN bun install --frozen-lockfile
RUN bun x vite build
